// Auto-generated by scripts/generate-font-index.ts
// Do not edit manually

export interface Font {
  name: string;
  weight: number;
  style: "normal" | "italic";
  load: () => Promise<Uint8Array>;
}

export const newComputerModernMath: Font[] = [
  {
    name: "New Computer Modern Math",
    weight: 400,
    style: "normal",
    load: async () => {
      const response = await fetch(new URL("./files/NewCMMath-Regular.otf", import.meta.url));
      return new Uint8Array(await response.arrayBuffer());
    },
  },
  {
    name: "New Computer Modern Math",
    weight: 700,
    style: "normal",
    load: async () => {
      const response = await fetch(new URL("./files/NewCMMath-Bold.otf", import.meta.url));
      return new Uint8Array(await response.arrayBuffer());
    },
  },
  {
    name: "New Computer Modern Math",
    weight: 450,
    style: "normal",
    load: async () => {
      const response = await fetch(new URL("./files/NewCMMath-Book.otf", import.meta.url));
      return new Uint8Array(await response.arrayBuffer());
    },
  },
];

export const newComputerModernMathRegular = newComputerModernMath.find((font) => font.weight === 400)!;
export const newComputerModernMathBold = newComputerModernMath.find((font) => font.weight === 700)!;
export const newComputerModernMathBook = newComputerModernMath.find((font) => font.weight === 450)!;

export const defaultFonts = [
  newComputerModernMathRegular,
  newComputerModernMathBold,
  newComputerModernMathBook,
];
