#!/usr/bin/env bun
/**
 * Font index generator for typst-wasm
 * Generates the font module for a target directory.
 */

import { mkdir, writeFile } from "fs/promises";
import { join, resolve } from "path";

// Font variant configurations
const FONT_VARIANTS = [
  { file: "NewCMMath-Regular", weight: 400, style: "normal" },
  { file: "NewCMMath-Bold", weight: 700, style: "normal" },
  { file: "NewCMMath-Book", weight: 450, style: "normal" },
] as const;

const FONT_DECLARATIONS = `declare module "*.otf" {
  const url: string;
  export default url;
}
`;

function resolveOutputDir(): string {
  const requestedDir = process.env.FONT_OUTPUT_DIR ?? process.argv[2];
  return requestedDir ? resolve(requestedDir) : join(process.cwd(), "src", "fonts");
}

async function generateFontIndex(): Promise<void> {
  const fontsDir = resolveOutputDir();
  const indexPath = join(fontsDir, "index.ts");
  const declarationsPath = join(fontsDir, "fonts.d.ts");

  await mkdir(fontsDir, { recursive: true });

  // Generate font objects
  const fontObjects = FONT_VARIANTS.map((v) => {
    return `  {
    name: "New Computer Modern Math",
    weight: ${v.weight},
    style: "${v.style}",
    load: async () => {
      const response = await fetch(new URL("./files/${v.file}.otf", import.meta.url));
      return new Uint8Array(await response.arrayBuffer());
    }
  }`;
  }).join(",\n");

  // Generate convenience exports
  const regularExport = `export const newComputerModernMathRegular = newComputerModernMath.find(f => f.weight === 400)!;`;
  const boldExport = `export const newComputerModernMathBold = newComputerModernMath.find(f => f.weight === 700)!;`;
  const bookExport = `export const newComputerModernMathBook = newComputerModernMath.find(f => f.weight === 450)!;`;

  const content = `// Auto-generated by scripts/generate-font-index.ts
// Do not edit manually

export interface Font {
  name: string;
  weight: number;
  style: 'normal' | 'italic';
  load: () => Promise<Uint8Array>;
}

export const newComputerModernMath: Font[] = [
${fontObjects}
];

${regularExport}
${boldExport}
${bookExport}

export const defaultFonts = [
  newComputerModernMathRegular,
  newComputerModernMathBold,
  newComputerModernMathBook,
];
`;

  await Promise.all([
    writeFile(indexPath, content),
    writeFile(declarationsPath, FONT_DECLARATIONS),
  ]);

  console.log(`[fonts] Generated ${fontsDir}`);
}

// Run if executed directly
if (import.meta.main) {
  generateFontIndex().catch((error) => {
    console.error("[fonts] Error generating index:", error);
    process.exit(1);
  });
}

export { generateFontIndex };
