#!/usr/bin/env bun
/**
 * Font index generator for typst-wasm
 * Generates src/fonts/index.ts with URL imports for each font variant
 */

import { writeFile } from "fs/promises";
import { join } from "path";

// Font variant configurations
const FONT_VARIANTS = [
  { file: "NewCMMath-Regular", weight: 400, style: "normal" },
  { file: "NewCMMath-Bold", weight: 700, style: "normal" },
  { file: "NewCMMath-Book", weight: 450, style: "normal" },
] as const;

async function generateFontIndex(): Promise<void> {
  const fontsDir = join(process.cwd(), "src", "fonts");
  const indexPath = join(fontsDir, "index.ts");

  // Generate font objects
  const fontObjects = FONT_VARIANTS.map((v) => {
    return `  {
    name: "New Computer Modern Math",
    weight: ${v.weight},
    style: "${v.style}",
    load: async () => {
      const response = await fetch(new URL("./files/${v.file}.otf", import.meta.url));
      return new Uint8Array(await response.arrayBuffer());
    }
  }`;
  }).join(",\n");

  // Generate convenience exports
  const regularExport = `export const newComputerModernMathRegular = newComputerModernMath.find(f => f.weight === 400)!;`;
  const boldExport = `export const newComputerModernMathBold = newComputerModernMath.find(f => f.weight === 700)!;`;
  const bookExport = `export const newComputerModernMathBook = newComputerModernMath.find(f => f.weight === 450)!;`;

  const content = `// Auto-generated by scripts/generate-font-index.ts
// Do not edit manually

export interface Font {
  name: string;
  weight: number;
  style: 'normal' | 'italic';
  load: () => Promise<Uint8Array>;
}

export const newComputerModernMath: Font[] = [
${fontObjects}
];

${regularExport}
${boldExport}
${bookExport}

export const defaultFonts = [
  newComputerModernMathRegular,
  newComputerModernMathBold,
  newComputerModernMathBook,
];
`;

  await writeFile(indexPath, content);
  console.log("[fonts] Generated src/fonts/index.ts");
}

// Run if executed directly
if (import.meta.main) {
  generateFontIndex().catch((error) => {
    console.error("[fonts] Error generating index:", error);
    process.exit(1);
  });
}

export { generateFontIndex };
